// packages/react/src/components/accordion.ts
import React from "react";

export type AccordionProps = React.DetailsHTMLAttributes<HTMLDetailsElement>;

export const Accordion = React.forwardRef<HTMLDetailsElement, AccordionProps>(
  function Accordion({ children, ...props }, ref) {
    return React.createElement(
      "details",
      {
        ...props,
        className:
          props.className
            ? `ore-accordion ${props.className}`
            : "ore-accordion",
        ref,
      },
      children,
    );
  },
);

// packages/svelte/src/components/accordion.svelte
<script lang="ts">
  import type { OreComponentProps } from "../types.js";

  export type AccordionProps = OreComponentProps<HTMLDetailsElement>;

  let { children, class: className, ...props }: AccordionProps = $props();
  let element: HTMLDetailsElement;

  export function getElement(): HTMLDetailsElement {
    return element;
  }
</script>

<details bind:this={element} class={`ore-accordion ${className ?? ""}`} {...props}>
  {@render children?.()}
</details>
