// packages/react/src/components/card.tsx
import React from "react";

export type CardProps = React.HTMLAttributes<HTMLElement>;

export const Card = React.forwardRef<HTMLElement, CardProps>(function Card(
  { children, ...props },
  ref,
) {
  return (
    <article
      {...props}
      ref={ref}
      className={props.className ? `ore-card ${props.className}` : "ore-card"}
    >
      {children}
    </article>
  );
});

// packages/svelte/src/components/card.svelte
<script lang="ts">
  import type { OreComponentProps } from "../types.js";

  export type CardProps = OreComponentProps<HTMLElement>;

  let { children, class: className, ...props }: CardProps = $props();
  let element: HTMLElement;

  export function getElement(): HTMLElement {
    return element;
  }
</script>

<article bind:this={element} class={`ore-card ${className ?? ""}`} {...props}>
  {@render children?.()}
</article>
