// packages/react/src/components/divider.tsx
import React from "react";

export type DividerProps = React.HTMLAttributes<HTMLHRElement>;

export const Divider = React.forwardRef<HTMLHRElement, DividerProps>(
  function Divider(props, ref): React.ReactElement {
    return <hr {...props} ref={ref} className={props.className ? `ore-divider ${props.className}` : "ore-divider"} />;
  },
);

// packages/svelte/src/components/divider.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";

  export type DividerProps = HTMLAttributes<HTMLHRElement>;

  let { class: className, ...props }: DividerProps = $props();

  export function getElement(): HTMLHRElement | undefined {
    return undefined;
  }
</script>

<hr class="ore-divider {className ?? ''}" {...props} />
