// packages/react/src/components/modal.ts
import { createComponent, type EventName } from "@lit/react";
import {
  OreModal as OreModalElement,
  type OreModalCloseDetail,
} from "oreui-web/modal";
import React from "react";

export const Modal = createComponent({
  react: React,
  tagName: "ore-modal",
  elementClass: OreModalElement,
  events: {
    onOpenChange: "open-change" as EventName<CustomEvent<boolean>>,
    onModalClose: "modal-close" as EventName<CustomEvent<OreModalCloseDetail>>,
  },
  displayName: "Modal",
});

export type ModalProps = React.ComponentProps<typeof Modal>;

// packages/svelte/src/components/modal.svelte
<script lang="ts">
  import "oreui-web/modal";
  import type { OreModal, OreModalCloseDetail } from "oreui-web/modal";
  import type { OreComponentProps } from "../types.js";

  export type ModalProps = OreComponentProps<
    OreModal,
    "defaultOpen" | "open"
  > & {
    onModalClose?: (event: CustomEvent<OreModalCloseDetail>) => void;
    onOpenChange?: (event: CustomEvent<boolean>) => void;
  };

  let {
    children,
    onModalClose,
    onOpenChange,
    ...props
  }: ModalProps = $props();
  let element: OreModal;

  export function getElement(): OreModal {
    return element;
  }
</script>

<ore-modal
  bind:this={element}
  onmodal-close={onModalClose}
  onopen-change={onOpenChange}
  {...props}
>
  {@render children?.()}
</ore-modal>
