// packages/solid/src/components/progress-ring.tsx
import { splitProps, type JSX } from "solid-js";

export type ProgressRingProps = JSX.HTMLAttributes<HTMLSpanElement>;

export function ProgressRing(props: ProgressRingProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);

  return <span {...rest} class={`ore-progress-ring ${local.class ?? ""}`} />;
}

// packages/svelte/src/components/progress-ring.svelte
<script lang="ts">
  import type { OreComponentProps } from "../types.js";

  export type ProgressRingProps = OreComponentProps<HTMLSpanElement>;

  let { children, class: className, ...props }: ProgressRingProps = $props();
  let element: HTMLSpanElement;

  export function getElement(): HTMLSpanElement {
    return element;
  }
</script>

<span bind:this={element} class={`ore-progress-ring ${className ?? ""}`} {...props}>
  {@render children?.()}
</span>
