// packages/solid/src/components/progress-bar.tsx
import { splitProps, type JSX } from "solid-js";

export type ProgressBarProps = JSX.ProgressHTMLAttributes<HTMLProgressElement>;

export function ProgressBar(props: ProgressBarProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);

  return (
    <progress
      {...rest}
      class={`ore-progress-bar ${local.class ?? ""}`}
    />
  );
}

// packages/svelte/src/components/progress-bar.svelte
<script lang="ts">
  import type { OreComponentProps } from "../types.js";

  export type ProgressBarProps = OreComponentProps<HTMLProgressElement>;

  let { children, class: className, ...props }: ProgressBarProps = $props();
  let element: HTMLProgressElement;

  export function getElement(): HTMLProgressElement {
    return element;
  }
</script>

<progress bind:this={element} class={`ore-progress-bar ${className ?? ""}`} {...props}>
  {@render children?.()}
</progress>
