// packages/react/src/components/radio.ts
import React from "react";

export type RadioProps = Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  "color" | "type"
> & {
  color?: string;
  labelClassName?: string;
};

export const Radio = React.forwardRef<HTMLInputElement, RadioProps>(
  function Radio(
    { children, color, labelClassName, className, ...props },
    ref,
  ): React.ReactElement {
    return React.createElement(
      "label",
      { className: labelClassName },
      React.createElement("input", {
        ...props,
        className: className ? `ore-radio ${className}` : "ore-radio",
        "data-color": color,
        ref,
        type: "radio",
      }),
      children,
    );
  },
);

// packages/svelte/src/components/radio.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";

  export type RadioProps = Omit<HTMLInputAttributes, "children" | "color" | "type"> & {
    children?: Snippet;
    color?: string;
    labelClass?: string;
  };

  let {
    children,
    class: className,
    color,
    labelClass,
    ...props
  }: RadioProps = $props();
  let element: HTMLInputElement;

  export function getElement(): HTMLInputElement {
    return element;
  }
</script>

<label class={labelClass}>
  <input bind:this={element} {...props} class="ore-radio {className ?? ''}" data-color={color} type="radio" />
  {@render children?.()}
</label>
