// packages/react/src/components/scrollbar.ts
import "oreui-web/scrollbar";
import React from "react";

export type ScrollbarProps = React.HTMLAttributes<HTMLDivElement>;

export const Scrollbar = React.forwardRef<HTMLDivElement, ScrollbarProps>(
  function Scrollbar(props, ref) {
    return React.createElement("div", {
      ...props,
      ref,
      className: props.className
        ? `ore-scrollbar ${props.className}`
        : "ore-scrollbar",
    });
  },
);

// packages/svelte/src/components/scrollbar.svelte
<script lang="ts">
  import "oreui-web/scrollbar";
  import type { OreComponentProps } from "../types.js";

  export type ScrollbarProps = OreComponentProps<HTMLDivElement>;

  let { children, class: className, ...props }: ScrollbarProps = $props();
  let element: HTMLDivElement;

  export function getElement(): HTMLDivElement {
    return element;
  }
</script>

<div bind:this={element} class={`ore-scrollbar ${className ?? ""}`} {...props}>
  {@render children?.()}
</div>
