// packages/solid/src/components/slider.tsx
import { syncSlider } from "oreui-web/slider";
import { createRenderEffect, splitProps, type JSX } from "solid-js";

export type SliderProps = Omit<
  JSX.InputHTMLAttributes<HTMLInputElement>,
  "color" | "type"
> & {
  color?: string;
  onValueChange?: (value: number) => void;
  orientation?: "horizontal" | "vertical";
  variant?: string;
};

export function Slider(props: SliderProps): JSX.Element {
  let element: HTMLInputElement | undefined;
  const [local, inputProps] = splitProps(props, [
    "class",
    "color",
    "onInput",
    "onValueChange",
    "orientation",
    "ref",
    "variant",
  ]);

  const sync = (node: HTMLInputElement): void => {
    element = node;
    if (typeof local.ref === "function") {
      local.ref(node);
    }
  };

  createRenderEffect(() => {
    inputProps.max;
    inputProps.min;
    inputProps.step;
    inputProps.value;
    if (element) {
      syncSlider(element);
    }
  });

  return (
    <input
      {...inputProps}
      class={`ore-slider ${local.class ?? ""}`}
      aria-orientation={local.orientation}
      data-color={local.color}
      data-orientation={local.orientation}
      data-variant={local.variant}
      onInput={(event) => {
        if (typeof local.onInput === "function") {
          local.onInput(event);
        }
        local.onValueChange?.(event.currentTarget.valueAsNumber);
      }}
      ref={sync}
      type="range"
    />
  );
}

// packages/svelte/src/components/slider.svelte
<script lang="ts">
  import { syncSlider } from "oreui-web/slider";
  import type { HTMLInputAttributes } from "svelte/elements";

  export type SliderProps = Omit<HTMLInputAttributes, "color" | "type" | "value"> & {
    color?: string;
    orientation?: "horizontal" | "vertical";
    value?: number;
    variant?: string;
  };

  let {
    class: className,
    color,
    max,
    min,
    oninput,
    orientation,
    step,
    value = $bindable(0),
    variant,
    ...props
  }: SliderProps = $props();
  let element: HTMLInputElement;

  $effect(() => {
    max;
    min;
    step;
    value;
    if (element) {
      syncSlider(element);
    }
  });

  function handleInput(
    event: Event & { currentTarget: EventTarget & HTMLInputElement },
  ): void {
    value = element.valueAsNumber;
    oninput?.(event);
  }

  export function getElement(): HTMLInputElement {
    return element;
  }
</script>

<input
  bind:this={element}
  bind:value
  {...props}
  class="ore-slider {className ?? ''}"
  aria-orientation={orientation}
  data-color={color}
  data-orientation={orientation}
  data-variant={variant}
  {max}
  {min}
  oninput={handleInput}
  {step}
  type="range"
/>
