// packages/solid/src/components/switch.tsx
import { splitProps, type JSX } from "solid-js";

export type SwitchProps = Omit<
  JSX.InputHTMLAttributes<HTMLInputElement>,
  "color" | "type"
> & {
  color?: string;
  labelClass?: string;
  onCheckedChange?: (checked: boolean) => void;
  variant?: string;
};

export function Switch(props: SwitchProps): JSX.Element {
  const [local, inputProps] = splitProps(props, [
    "children",
    "class",
    "color",
    "labelClass",
    "onCheckedChange",
    "onInput",
    "variant",
  ]);

  return (
    <label class={local.labelClass}>
      <input
        {...inputProps}
        class={`ore-switch ${local.class ?? ""}`}
        data-color={local.color}
        data-variant={local.variant}
        onInput={(event) => {
          if (typeof local.onInput === "function") {
            local.onInput(event);
          }
          local.onCheckedChange?.(event.currentTarget.checked);
        }}
        role="switch"
        type="checkbox"
      />
      {local.children}
    </label>
  );
}

// packages/svelte/src/components/switch.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";

  export type SwitchProps = Omit<HTMLInputAttributes, "children" | "color" | "type"> & {
    checked?: boolean;
    children?: Snippet;
    color?: string;
    labelClass?: string;
    variant?: string;
  };

  let {
    children,
    checked = $bindable(false),
    class: className,
    color,
    labelClass,
    oninput,
    variant,
    ...props
  }: SwitchProps = $props();
  let element: HTMLInputElement;

  function handleInput(
    event: Event & { currentTarget: EventTarget & HTMLInputElement },
  ): void {
    checked = element.checked;
    oninput?.(event);
  }

  export function getElement(): HTMLInputElement {
    return element;
  }
</script>

<label class={labelClass}>
  <input
    bind:this={element}
    bind:checked
    {...props}
    class="ore-switch {className ?? ''}"
    data-color={color}
    data-variant={variant}
    oninput={handleInput}
    role="switch"
    type="checkbox"
  />
  {@render children?.()}
</label>
