// packages/react/src/components/tag.tsx
import React from "react";

export type TagProps = React.HTMLAttributes<HTMLSpanElement> & {
  variant?: string;
  outlined?: boolean;
};

export const Tag = React.forwardRef<HTMLSpanElement, TagProps>(function Tag(
  { children, variant, outlined, ...props },
  ref,
) {
  return (
    <span
      {...props}
      ref={ref}
      className={props.className ? `ore-tag ${props.className}` : "ore-tag"}
      data-variant={variant}
      data-outlined={outlined ? "" : undefined}
    >
      {children}
    </span>
  );
});

// packages/svelte/src/components/tag.svelte
<script lang="ts">
  import type { OreComponentProps } from "../types.js";

  export type TagProps = OreComponentProps<HTMLSpanElement> & {
    variant?: string;
    outlined?: boolean;
  };

  let { children, variant, outlined, class: className, ...props }: TagProps = $props();
  let element: HTMLSpanElement;

  export function getElement(): HTMLSpanElement {
    return element;
  }
</script>

<span bind:this={element} class={`ore-tag ${className ?? ""}`} data-variant={variant} data-outlined={outlined ? "" : undefined} {...props}>
  {@render children?.()}
</span>
