// packages/solid/src/components/textarea.tsx
import { createRenderEffect, splitProps, type JSX } from "solid-js";

export type TextareaProps = Omit<
  JSX.TextareaHTMLAttributes<HTMLTextAreaElement>,
  "children" | "oninput" | "value"
> & {
  children?: JSX.Element;
  description?: string;
  error?: string;
  label?: string;
  onInput?: (
    event: InputEvent & { currentTarget: HTMLTextAreaElement },
  ) => void;
  value?: string;
  onValueChange?: (value: string) => void;
};

export function Textarea(props: TextareaProps): JSX.Element {
  const [local, textareaProps] = splitProps(props, [
    "children",
    "description",
    "error",
    "id",
    "label",
    "class",
    "onInput",
    "onValueChange",
    "style",
    "value",
  ]);
  let element: HTMLTextAreaElement | undefined;
  const generatedId = `ore-textarea-${crypto.randomUUID()}`;

  createRenderEffect(() => {
    element?.setCustomValidity(local.error ?? "");
  });

  const textareaId = () => local.id ?? generatedId;
  const descriptionId = () =>
    local.description ? `${textareaId()}-description` : undefined;
  const errorId = () => (local.error ? `${textareaId()}-error` : undefined);

  return (
    <div
      class="ore-textarea"
      classList={{ [local.class ?? ""]: true }}
      style={local.style}
    >
      {local.label ? (
        <label class="ore-textarea-label" for={textareaId()}>
          {local.label}
        </label>
      ) : null}
      <span class="ore-textarea-control">
        {local.children}
        <textarea
          {...textareaProps}
          aria-describedby={
            [descriptionId(), errorId()].filter(Boolean).join(" ") || undefined
          }
          aria-invalid={local.error ? "true" : undefined}
          class="ore-textarea-input"
          id={textareaId()}
          onInput={(event) => {
            local.onInput?.(event);
            local.onValueChange?.(event.currentTarget.value);
          }}
          ref={(value) => {
            element = value;
          }}
          value={local.value}
        />
      </span>
      {local.description ? (
        <span class="ore-textarea-description" id={descriptionId()}>
          {local.description}
        </span>
      ) : null}
      {local.error ? (
        <span class="ore-textarea-error" id={errorId()} aria-live="polite">
          {local.error}
        </span>
      ) : null}
    </div>
  );
}

// packages/svelte/src/components/textarea.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLTextareaAttributes } from "svelte/elements";

  export type TextareaProps = Omit<HTMLTextareaAttributes, "children" | "value"> & {
    children?: Snippet;
    value?: string;
    onChange?: (event: Event) => void;
    onInput?: (event: Event) => void;
    description?: string;
    error?: string;
    label?: string;
  };

  let {
    children,
    description,
    error,
    label,
    class: className,
    value = $bindable(""),
    onChange,
    onInput,
    style,
    ...props
  }: TextareaProps = $props();
  let element: HTMLTextAreaElement;
  const generatedTextareaId = `ore-textarea-${crypto.randomUUID()}`;

  const textareaId = $derived(props.id ?? generatedTextareaId);
  const descriptionId = $derived(description ? `${textareaId}-description` : undefined);
  const errorId = $derived(error ? `${textareaId}-error` : undefined);

  function handleInput(event: Event): void {
    value = element.value;
    onInput?.(event);
  }

  $effect(() => {
    element?.setCustomValidity(error ?? "");
  });

  export function getElement(): HTMLTextAreaElement {
    return element;
  }
</script>

<div class="ore-textarea {className ?? ''}" {style}>
  {#if label}
    <label class="ore-textarea-label" for={textareaId}>{label}</label>
  {/if}
  <span class="ore-textarea-control">
    {@render children?.()}
    <textarea
      bind:this={element}
      bind:value
      {...props}
      aria-describedby={[descriptionId, errorId].filter(Boolean).join(" ") || undefined}
      aria-invalid={error ? "true" : undefined}
      class="ore-textarea-input"
      id={textareaId}
      onchange={onChange}
      oninput={handleInput}
    ></textarea>
  </span>
  {#if description}
    <span class="ore-textarea-description" id={descriptionId}>{description}</span>
  {/if}
  {#if error}
    <span class="ore-textarea-error" id={errorId} aria-live="polite">{error}</span>
  {/if}
</div>
