// packages/react/src/components/toggles.ts
import React from "react";

export { TabButton, type TabButtonProps } from "./tab-button.js";

export type TogglesProps = React.HTMLAttributes<HTMLDivElement>;

export const Toggles = React.forwardRef<HTMLDivElement, TogglesProps>(
  function Toggles({ children, className, ...props }, ref) {
    return React.createElement(
      "div",
      {
        ...props,
        className: className ? `ore-toggles ${className}` : "ore-toggles",
        ref,
        role: "tablist",
      },
      children,
    );
  },
);

// packages/svelte/src/components/toggles.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import type { OreComponentProps } from "../types.js";

  export type TogglesProps = HTMLAttributes<HTMLDivElement>;

  let { children, ...props }: TogglesProps = $props();
  let element: HTMLDivElement;

  export function getElement(): HTMLDivElement {
    return element;
  }
</script>

<div class="ore-toggles" bind:this={element} role="tablist" {...props}>
  {@render children?.()}
</div>
