// packages/solid/src/components/tooltip.tsx
import "oreui-web/tooltip";

import type { OreTooltipSide } from "oreui-web/tooltip";
import { onCleanup, onMount, splitProps, type JSX } from "solid-js";

export type TooltipProps = JSX.HTMLAttributes<HTMLSpanElement> & {
  defaultOpen?: boolean;
  delay?: number;
  onOpenChange?: (event: CustomEvent<boolean>) => void;
  open?: boolean;
  side?: OreTooltipSide;
};

export function Tooltip(props: TooltipProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "class",
    "defaultOpen",
    "delay",
    "onOpenChange",
    "open",
    "ref",
    "side",
  ]);
  let element: HTMLSpanElement | undefined;

  onMount(() => {
    if (!element) {
      return;
    }

    const listener = (event: Event): void => {
      local.onOpenChange?.(event as CustomEvent<boolean>);
    };
    element.addEventListener("oreui:openchange", listener);
    onCleanup(() => element?.removeEventListener("oreui:openchange", listener));
  });

  return (
    <span
      {...rest}
      class={`ore-tooltip ${local.class ?? ""}`}
      data-default-open={local.defaultOpen ? "" : undefined}
      data-delay={local.delay}
      data-open={local.open === undefined ? undefined : String(local.open)}
      data-side={local.side ?? "top"}
      ref={(value) => {
        element = value;
        if (typeof local.ref === "function") {
          local.ref(value);
        }
      }}
    />
  );
}

// packages/svelte/src/components/tooltip.svelte
<script lang="ts">
  import "oreui-web/tooltip";
  import type { OreTooltipSide } from "oreui-web/tooltip";
  import { onMount } from "svelte";
  import type { OreComponentProps } from "../types.js";

  export type TooltipProps = OreComponentProps<HTMLSpanElement> & {
    defaultOpen?: boolean;
    delay?: number;
    open?: boolean;
    side?: OreTooltipSide;
    onOpenChange?: (event: CustomEvent<boolean>) => void;
  };

  let {
    children,
    class: className,
    defaultOpen = false,
    delay,
    open,
    side = "top",
    onOpenChange,
    ...props
  }: TooltipProps = $props();
  let element: HTMLSpanElement;

  onMount(() => {
    const listener = (event: Event): void => {
      onOpenChange?.(event as CustomEvent<boolean>);
    };

    element.addEventListener("oreui:openchange", listener);
    return () => element.removeEventListener("oreui:openchange", listener);
  });

  export function getElement(): HTMLSpanElement {
    return element;
  }
</script>

<span
  bind:this={element}
  class={`ore-tooltip ${className ?? ""}`}
  data-default-open={defaultOpen ? "" : undefined}
  data-delay={delay}
  data-open={open === undefined ? undefined : String(open)}
  data-side={side}
  {...props}
>
  {@render children?.()}
</span>
