// packages/svelte/src/components/button.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from "svelte/elements";

  export type ButtonProps = HTMLButtonAttributes & {
    color?: string;
    loading?: boolean;
    variant?: string;
  };

  let { children, ...props }: ButtonProps = $props();
  let element: HTMLButtonElement;

  export function getElement(): HTMLButtonElement {
    return element;
  }
</script>

<button bind:this={element} {...props} class="ore-button {props.class ?? ''}" data-color={props.color} data-loading={props.loading ? "" : undefined} data-variant={props.variant} aria-busy={props.loading || undefined} disabled={props.disabled || props.loading}>
  {@render children?.()}
</button>

// packages/react/src/components/button.ts
import React from "react";

export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  color?: string;
  loading?: boolean;
  variant?: string;
};

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  function Button(
    { color, loading, variant, children, className, ...props },
    ref,
  ): React.ReactElement {
    return React.createElement(
      "button",
      {
        ...props,
        "aria-busy": loading || undefined,
        "data-color": color,
        "data-loading": loading ? "" : undefined,
        "data-variant": variant,
        className: className ? `ore-button ${className}` : "ore-button",
        disabled: props.disabled || loading,
        ref,
      },
      children,
    );
  },
);
