// packages/svelte/src/components/card.svelte
<script lang="ts">
  import "oreui-web/card";
  import type { OreCard } from "oreui-web/card";
  import type { OreComponentProps } from "../types.js";

  export type CardProps = OreComponentProps<OreCard>;

  let { children, ...props }: CardProps = $props();
  let element: OreCard;

  export function getElement(): OreCard {
    return element;
  }
</script>

<ore-card bind:this={element} {...props}>
  {@render children?.()}
</ore-card>

// packages/react/src/components/card.ts
import { createComponent } from "@lit/react";
import { OreCard as OreCardElement } from "oreui-web/card";
import React from "react";

export const Card = createComponent({
  react: React,
  tagName: "ore-card",
  elementClass: OreCardElement,
  displayName: "Card",
});

export type CardProps = React.ComponentProps<typeof Card>;
