// packages/svelte/src/components/container.svelte
<script lang="ts">
  import type { OreContainerVariant } from "oreui-web/container";
  import type { OreComponentProps } from "../types.js";

  export type ContainerProps = OreComponentProps<HTMLDivElement> & {
    variant?: OreContainerVariant;
  };

  let { children, variant = "dark", class: className, ...props }: ContainerProps = $props();
  let element: HTMLDivElement;

  export function getElement(): HTMLDivElement {
    return element;
  }
</script>

<div bind:this={element} class={`ore-container ${className ?? ""}`} data-variant={variant} {...props}>
  {@render children?.()}
</div>

// packages/react/src/components/container.tsx
import React from "react";

import type { OreContainerVariant } from "oreui-web/container";

export type ContainerProps = React.HTMLAttributes<HTMLDivElement> & {
  variant?: OreContainerVariant;
};

export const Container = React.forwardRef<HTMLDivElement, ContainerProps>(
  function Container({ children, variant = "dark", ...props }, ref) {
    return (
      <div
        {...props}
        ref={ref}
        className={
          props.className ? `ore-container ${props.className}` : "ore-container"
        }
        data-variant={variant}
      >
        {children}
      </div>
    );
  },
);
