// packages/solid/src/components/container.tsx
import type { OreContainerVariant } from "oreui-web/container";
import type { JSX } from "solid-js";

export type ContainerProps = JSX.HTMLAttributes<HTMLDivElement> & {
  variant?: OreContainerVariant;
};

export function Container(props: ContainerProps): JSX.Element {
  const { variant = "dark", class: className, ...rest } = props;

  return (
    <div
      {...rest}
      class={`ore-container ${className ?? ""}`}
      data-variant={variant}
    />
  );
}

// packages/react/src/components/container.tsx
import React from "react";

import type { OreContainerVariant } from "oreui-web/container";

export type ContainerProps = React.HTMLAttributes<HTMLDivElement> & {
  variant?: OreContainerVariant;
};

export const Container = React.forwardRef<HTMLDivElement, ContainerProps>(
  function Container({ children, variant = "dark", ...props }, ref) {
    return (
      <div
        {...props}
        ref={ref}
        className={
          props.className ? `ore-container ${props.className}` : "ore-container"
        }
        data-variant={variant}
      >
        {children}
      </div>
    );
  },
);
