// packages/svelte/src/components/divider.svelte
<script lang="ts">
  import "oreui-web/divider";
  import type { OreDivider } from "oreui-web/divider";
  import type { OreComponentProps } from "../types.js";

  export type DividerProps = OreComponentProps<OreDivider>;

  let { children, ...props }: DividerProps = $props();
  let element: OreDivider;

  export function getElement(): OreDivider {
    return element;
  }
</script>

<ore-divider bind:this={element} {...props}>
  {@render children?.()}
</ore-divider>

// packages/react/src/components/divider.ts
import { createComponent } from "@lit/react";
import { OreDivider as OreDividerElement } from "oreui-web/divider";
import React from "react";

export const Divider = createComponent({
  react: React,
  tagName: "ore-divider",
  elementClass: OreDividerElement,
  displayName: "Divider",
});

export type DividerProps = React.ComponentProps<typeof Divider>;
