// packages/svelte/src/components/dropdown.svelte
<script lang="ts">
  import "oreui-web/dropdown";
  import type {
    OreDropdownChangeDetail,
    OreDropdownVariant,
  } from "oreui-web/dropdown";
  import type { OreComponentProps } from "../types.js";

  export type DropdownProps = OreComponentProps<HTMLDivElement> & {
    value?: string;
    variant?: OreDropdownVariant;
    onChange?: (event: CustomEvent<OreDropdownChangeDetail>) => void;
  };

  let {
    children,
    class: className,
    value = $bindable(""),
    variant = "borderless",
    onChange,
    ...props
  }: DropdownProps = $props();
  let element: HTMLDivElement;

  function handleChange(event: Event): void {
    const changeEvent = event as CustomEvent<OreDropdownChangeDetail>;

    value = changeEvent.detail.value;
    onChange?.(changeEvent);
  }

  export function getElement(): HTMLDivElement {
    return element;
  }
</script>

<div
  bind:this={element}
  class={`ore-dropdown ${className ?? ""}`}
  data-value={value}
  data-variant={variant}
  onchange={handleChange}
  {...props}
>
  {@render children?.()}
</div>

// packages/react/src/components/dropdown.ts
import "oreui-web/dropdown";
import type {
  OreDropdownChangeDetail,
  OreDropdownVariant,
} from "oreui-web/dropdown";
import React, { useEffect, useImperativeHandle, useRef } from "react";

export type DropdownProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "onChange"
> & {
  onChange?: (event: CustomEvent<OreDropdownChangeDetail>) => void;
  value?: string;
  variant?: OreDropdownVariant;
};

export const Dropdown = React.forwardRef<HTMLDivElement, DropdownProps>(
  function Dropdown(
    { children, className, onChange, value, variant, ...props },
    ref,
  ) {
    const elementRef = useRef<HTMLDivElement>(null);

    useImperativeHandle(ref, () => elementRef.current as HTMLDivElement);
    useEffect(() => {
      const element = elementRef.current;

      if (!element || !onChange) {
        return;
      }

      const listener = (event: Event) =>
        onChange(event as CustomEvent<OreDropdownChangeDetail>);
      element.addEventListener("change", listener);
      return () => element.removeEventListener("change", listener);
    }, [onChange]);

    return React.createElement(
      "div",
      {
        ...props,
        "data-value": value,
        "data-variant": variant ?? "borderless",
        className: className ? `ore-dropdown ${className}` : "ore-dropdown",
        ref: elementRef,
      },
      children,
    );
  },
);
