// packages/svelte/src/components/navbar.svelte
<script lang="ts">
  import "oreui-web/navbar";
  import type { OreNavbar } from "oreui-web/navbar";
  import type { OreComponentProps } from "../types.js";

  export type NavbarProps = OreComponentProps<OreNavbar>;

  let { children, ...props }: NavbarProps = $props();
  let element: OreNavbar;

  export function getElement(): OreNavbar {
    return element;
  }
</script>

<ore-navbar bind:this={element} {...props}>
  {@render children?.()}
</ore-navbar>

// packages/react/src/components/navbar.ts
import { createComponent } from "@lit/react";
import { OreNavbar as OreNavbarElement } from "oreui-web/navbar";
import React from "react";

export const Navbar = createComponent({
  react: React,
  tagName: "ore-navbar",
  elementClass: OreNavbarElement,
  displayName: "Navbar",
});

export type NavbarProps = React.ComponentProps<typeof Navbar>;
