// packages/svelte/src/components/navbar.svelte
<script lang="ts">
  import type { OreComponentProps } from "../types.js";

  export type NavbarProps = OreComponentProps<HTMLElement>;

  let { children, class: className, ...props }: NavbarProps = $props();
  let element: HTMLElement;

  export function getElement(): HTMLElement {
    return element;
  }
</script>

<nav bind:this={element} class={`ore-navbar ${className ?? ""}`} {...props}>
  {@render children?.()}
</nav>

// packages/react/src/components/navbar.tsx
import React from "react";

export type NavbarProps = React.HTMLAttributes<HTMLElement>;

export const Navbar = React.forwardRef<HTMLElement, NavbarProps>(
  function Navbar({ children, ...props }, ref) {
    return (
      <nav
        {...props}
        ref={ref}
        className={
          props.className ? `ore-navbar ${props.className}` : "ore-navbar"
        }
      >
        {children}
      </nav>
    );
  },
);
