// packages/solid/src/components/progress-ring.tsx
import { splitProps, type JSX } from "solid-js";

export type ProgressRingProps = JSX.HTMLAttributes<HTMLSpanElement>;

export function ProgressRing(props: ProgressRingProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);

  return <span {...rest} class={`ore-progress-ring ${local.class ?? ""}`} />;
}

// packages/react/src/components/progress-ring.ts
import React from "react";

export type ProgressRingProps = React.HTMLAttributes<HTMLSpanElement>;

export const ProgressRing = React.forwardRef<
  HTMLSpanElement,
  ProgressRingProps
>(function ProgressRing(props, ref) {
  return React.createElement("span", {
    ...props,
    ref,
    className: props.className
      ? `ore-progress-ring ${props.className}`
      : "ore-progress-ring",
  });
});
