// packages/svelte/src/components/radio-group.svelte
<script lang="ts">
  import "oreui-web/radio-group";
  import type { OreRadioGroup } from "oreui-web/radio-group";
  import type { OreComponentProps } from "../types.js";

  export type RadioGroupProps = OreComponentProps<OreRadioGroup>;

  let { children, ...props }: RadioGroupProps = $props();
  let element: OreRadioGroup;

  export function getElement(): OreRadioGroup {
    return element;
  }
</script>

<ore-radio-group bind:this={element} {...props}>
  {@render children?.()}
</ore-radio-group>

// packages/react/src/components/radio-group.ts
import { createComponent } from "@lit/react";
import { OreRadioGroup as OreRadioGroupElement } from "oreui-web/radio-group";
import React from "react";

export { Radio, type RadioProps } from "./radio.js";

export const RadioGroup = createComponent({
  react: React,
  tagName: "ore-radio-group",
  elementClass: OreRadioGroupElement,
  displayName: "RadioGroup",
});

export type RadioGroupProps = React.ComponentProps<typeof RadioGroup>;
