// packages/solid/src/components/radio-group.tsx
import { splitProps, type JSX } from "solid-js";

export type RadioGroupProps = JSX.FieldsetHTMLAttributes<HTMLFieldSetElement>;

export function RadioGroup(props: RadioGroupProps): JSX.Element {
  const [local, fieldsetProps] = splitProps(props, ["class"]);

  return (
    <fieldset
      {...fieldsetProps}
      class={["ore-radio-group", local.class].filter(Boolean).join(" ")}
    />
  );
}

// packages/react/src/components/radio-group.ts
import React from "react";

export { Radio, type RadioProps } from "./radio.js";

export type RadioGroupProps = React.FieldsetHTMLAttributes<HTMLFieldSetElement>;

export const RadioGroup = React.forwardRef<
  HTMLFieldSetElement,
  RadioGroupProps
>(function RadioGroup({ className, ...props }, ref): React.ReactElement {
  return React.createElement("fieldset", {
    ...props,
    className: ["ore-radio-group", className].filter(Boolean).join(" "),
    ref,
  });
});
