// packages/solid/src/components/scrollbar.tsx
import "oreui-web/scrollbar";
import { splitProps, type JSX } from "solid-js";

export type ScrollbarProps = JSX.HTMLAttributes<HTMLDivElement>;

export function Scrollbar(props: ScrollbarProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);

  return <div {...rest} class={`ore-scrollbar ${local.class ?? ""}`} />;
}

// packages/react/src/components/scrollbar.ts
import "oreui-web/scrollbar";
import React from "react";

export type ScrollbarProps = React.HTMLAttributes<HTMLDivElement>;

export const Scrollbar = React.forwardRef<HTMLDivElement, ScrollbarProps>(
  function Scrollbar(props, ref) {
    return React.createElement("div", {
      ...props,
      ref,
      className: props.className
        ? `ore-scrollbar ${props.className}`
        : "ore-scrollbar",
    });
  },
);
