// packages/svelte/src/components/spinner.svelte
<script lang="ts">
  import type { OreComponentProps } from "../types.js";

  export type SpinnerProps = OreComponentProps<HTMLSpanElement>;

  let { children, class: className, "aria-hidden": ariaHidden, "aria-label": ariaLabel, ...props }: SpinnerProps = $props();
  let element: HTMLSpanElement;

  export function getElement(): HTMLSpanElement {
    return element;
  }
</script>

<span
  bind:this={element}
  class={`ore-spinner ${className ?? ""}`}
  role={ariaHidden ? undefined : "status"}
  aria-hidden={ariaHidden}
  aria-label={ariaHidden ? undefined : (ariaLabel ?? "Loading")}
  {...props}
>
  {@render children?.()}
</span>

// packages/react/src/components/spinner.ts
import React from "react";

export type SpinnerProps = React.HTMLAttributes<HTMLSpanElement>;

export const Spinner = React.forwardRef<HTMLSpanElement, SpinnerProps>(
  function Spinner(
    { "aria-hidden": ariaHidden, "aria-label": ariaLabel, ...props },
    ref,
  ) {
    return React.createElement("span", {
      ...props,
      ref,
      className: props.className
        ? `ore-spinner ${props.className}`
        : "ore-spinner",
      role: ariaHidden ? undefined : "status",
      "aria-hidden": ariaHidden,
      "aria-label": ariaHidden ? undefined : (ariaLabel ?? "Loading"),
    });
  },
);
