// packages/solid/src/components/spinner.tsx
import { splitProps, type JSX } from "solid-js";

export type SpinnerProps = JSX.HTMLAttributes<HTMLSpanElement>;

export function Spinner(props: SpinnerProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "class",
    "aria-hidden",
    "aria-label",
  ]);

  return (
    <span
      {...rest}
      class={`ore-spinner ${local.class ?? ""}`}
      role={local["aria-hidden"] ? undefined : "status"}
      aria-hidden={local["aria-hidden"]}
      aria-label={
        local["aria-hidden"] ? undefined : (local["aria-label"] ?? "Loading")
      }
    />
  );
}

// packages/react/src/components/spinner.ts
import React from "react";

export type SpinnerProps = React.HTMLAttributes<HTMLSpanElement>;

export const Spinner = React.forwardRef<HTMLSpanElement, SpinnerProps>(
  function Spinner(
    { "aria-hidden": ariaHidden, "aria-label": ariaLabel, ...props },
    ref,
  ) {
    return React.createElement("span", {
      ...props,
      ref,
      className: props.className
        ? `ore-spinner ${props.className}`
        : "ore-spinner",
      role: ariaHidden ? undefined : "status",
      "aria-hidden": ariaHidden,
      "aria-label": ariaHidden ? undefined : (ariaLabel ?? "Loading"),
    });
  },
);
