// packages/solid/src/components/switch.tsx
import { splitProps, type JSX } from "solid-js";

export type SwitchProps = Omit<
  JSX.InputHTMLAttributes<HTMLInputElement>,
  "color" | "type"
> & {
  color?: string;
  labelClass?: string;
  onCheckedChange?: (checked: boolean) => void;
  variant?: string;
};

export function Switch(props: SwitchProps): JSX.Element {
  const [local, inputProps] = splitProps(props, [
    "children",
    "class",
    "color",
    "labelClass",
    "onCheckedChange",
    "onInput",
    "variant",
  ]);

  return (
    <label class={local.labelClass}>
      <input
        {...inputProps}
        class={`ore-switch ${local.class ?? ""}`}
        data-color={local.color}
        data-variant={local.variant}
        onInput={(event) => {
          if (typeof local.onInput === "function") {
            local.onInput(event);
          }
          local.onCheckedChange?.(event.currentTarget.checked);
        }}
        role="switch"
        type="checkbox"
      />
      {local.children}
    </label>
  );
}

// packages/react/src/components/switch.ts
import React from "react";

export type SwitchProps = Omit<
  React.InputHTMLAttributes<HTMLInputElement>,
  "color" | "type"
> & {
  color?: string;
  labelClassName?: string;
  variant?: string;
};

export const Switch = React.forwardRef<HTMLInputElement, SwitchProps>(
  function Switch(
    { children, color, labelClassName, className, variant, ...props },
    ref,
  ): React.ReactElement {
    return React.createElement(
      "label",
      { className: labelClassName },
      React.createElement("input", {
        ...props,
        className: className ? `ore-switch ${className}` : "ore-switch",
        "data-color": color,
        "data-variant": variant,
        ref,
        role: "switch",
        type: "checkbox",
      }),
      children,
    );
  },
);
