// packages/solid/src/components/tab-button.tsx
import type { JSX } from "solid-js";

export type TabButtonProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> & {
  palette?: "default" | "toggle";
  selected?: boolean;
  variant?: string;
};

export function TabButton(props: TabButtonProps): JSX.Element {
  return (
    <button
      {...props}
      class="ore-tab-button"
      aria-selected={props.selected}
      data-palette={props.palette}
      data-variant={props.variant}
      role="tab"
    />
  );
}

// packages/react/src/components/tab-button.ts
import React from "react";

export type TabButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  palette?: "default" | "toggle";
  selected?: boolean;
  variant?: string;
};

export const TabButton = React.forwardRef<HTMLButtonElement, TabButtonProps>(
  function TabButton({ palette, selected, variant, className, ...props }, ref) {
    return React.createElement("button", {
      ...props,
      "aria-selected": selected,
      className: className ? `ore-tab-button ${className}` : "ore-tab-button",
      "data-palette": palette,
      "data-variant": variant,
      ref,
      role: "tab",
    });
  },
);
