// packages/svelte/src/components/tab-bar.svelte
<script lang="ts">
  import "oreui-web/tab-bar";
  import type { OreTabBar } from "oreui-web/tab-bar";
  import type { OreComponentProps } from "../types.js";

  export type TabBarProps = OreComponentProps<OreTabBar>;

  let { children, ...props }: TabBarProps = $props();
  let element: OreTabBar;

  export function getElement(): OreTabBar {
    return element;
  }
</script>

<ore-tab-bar bind:this={element} {...props}>
  {@render children?.()}
</ore-tab-bar>

// packages/react/src/components/tab-bar.ts
import { createComponent } from "@lit/react";
import { OreTabBar as OreTabBarElement } from "oreui-web/tab-bar";
import React from "react";

export { TabButton, type TabButtonProps } from "./tab-button.js";

export const TabBar = createComponent({
  react: React,
  tagName: "ore-tab-bar",
  elementClass: OreTabBarElement,
  displayName: "TabBar",
});

export type TabBarProps = React.ComponentProps<typeof TabBar>;
