// packages/react/src/components/button.ts
import React from "react";

export type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement> & {
  color?: string;
  loading?: boolean;
  variant?: string;
};

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  function Button(
    { color, loading, variant, children, className, ...props },
    ref,
  ): React.ReactElement {
    return React.createElement(
      "button",
      {
        ...props,
        "aria-busy": loading || undefined,
        "data-color": color,
        "data-loading": loading ? "" : undefined,
        "data-variant": variant,
        className: className ? `ore-button ${className}` : "ore-button",
        disabled: props.disabled || loading,
        ref,
      },
      children,
    );
  },
);

// packages/solid/src/components/button.tsx
import type { JSX } from "solid-js";

export type ButtonProps = JSX.ButtonHTMLAttributes<HTMLButtonElement> & {
  color?: string;
  loading?: boolean;
  variant?: string;
};

export function Button(props: ButtonProps): JSX.Element {
  const dataProps = {
    "data-color": props.color,
    "data-loading": props.loading ? "" : undefined,
    "data-variant": props.variant,
  };

  return (
    <button
      {...props}
      class={`ore-button ${props.class ?? ""}`}
      {...dataProps}
      aria-busy={props.loading || undefined}
      disabled={props.disabled || props.loading}
    />
  );
}
