// packages/svelte/src/components/checkbox.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";

  export type CheckboxProps = Omit<HTMLInputAttributes, "children" | "color" | "type"> & {
    checked?: boolean;
    children?: Snippet;
    color?: string;
    labelClass?: string;
  };

  let {
    children,
    checked = $bindable(false),
    class: className,
    color,
    labelClass,
    oninput,
    ...props
  }: CheckboxProps = $props();
  let element: HTMLInputElement;

  function handleInput(
    event: Event & { currentTarget: EventTarget & HTMLInputElement },
  ): void {
    checked = element.checked;
    oninput?.(event);
  }

  export function getElement(): HTMLInputElement {
    return element;
  }
</script>

<label class={labelClass}>
  <input bind:this={element} bind:checked {...props} class="ore-checkbox {className ?? ''}" data-color={color} oninput={handleInput} type="checkbox" />
  {@render children?.()}
</label>

// packages/solid/src/components/checkbox.tsx
import { splitProps, type JSX } from "solid-js";

export type CheckboxProps = Omit<
  JSX.InputHTMLAttributes<HTMLInputElement>,
  "color" | "type"
> & {
  color?: string;
  labelClass?: string;
  onCheckedChange?: (checked: boolean) => void;
};

export function Checkbox(props: CheckboxProps): JSX.Element {
  const [local, inputProps] = splitProps(props, [
    "children",
    "class",
    "color",
    "labelClass",
    "onCheckedChange",
    "onInput",
  ]);

  return (
    <label class={local.labelClass}>
      <input
        {...inputProps}
        class={`ore-checkbox ${local.class ?? ""}`}
        data-color={local.color}
        onInput={(event) => {
          if (typeof local.onInput === "function") {
            local.onInput(event);
          }
          local.onCheckedChange?.(event.currentTarget.checked);
        }}
        type="checkbox"
      />
      {local.children}
    </label>
  );
}
