// packages/react/src/components/dropdown.ts
import "oreui-web/dropdown";
import type {
  OreDropdownChangeDetail,
  OreDropdownVariant,
} from "oreui-web/dropdown";
import React, { useEffect, useImperativeHandle, useRef } from "react";

export type DropdownProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  "onChange"
> & {
  onChange?: (event: CustomEvent<OreDropdownChangeDetail>) => void;
  value?: string;
  variant?: OreDropdownVariant;
};

export const Dropdown = React.forwardRef<HTMLDivElement, DropdownProps>(
  function Dropdown(
    { children, className, onChange, value, variant, ...props },
    ref,
  ) {
    const elementRef = useRef<HTMLDivElement>(null);

    useImperativeHandle(ref, () => elementRef.current as HTMLDivElement);
    useEffect(() => {
      const element = elementRef.current;

      if (!element || !onChange) {
        return;
      }

      const listener = (event: Event) =>
        onChange(event as CustomEvent<OreDropdownChangeDetail>);
      element.addEventListener("change", listener);
      return () => element.removeEventListener("change", listener);
    }, [onChange]);

    return React.createElement(
      "div",
      {
        ...props,
        "data-value": value,
        "data-variant": variant ?? "borderless",
        className: className ? `ore-dropdown ${className}` : "ore-dropdown",
        ref: elementRef,
      },
      children,
    );
  },
);

// packages/solid/src/components/dropdown.tsx
import "oreui-web/dropdown";

import type {
  OreDropdownChangeDetail,
  OreDropdownVariant,
} from "oreui-web/dropdown";
import { onCleanup, onMount, splitProps, type JSX } from "solid-js";

export type DropdownProps = Omit<
  JSX.HTMLAttributes<HTMLDivElement>,
  "onChange"
> & {
  onChange?: (event: CustomEvent<OreDropdownChangeDetail>) => void;
  onValueChange?: (value: string) => void;
  value?: string;
  variant?: OreDropdownVariant;
};

export function Dropdown(props: DropdownProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "class",
    "onChange",
    "onValueChange",
    "ref",
    "value",
    "variant",
  ]);
  let element: HTMLDivElement | undefined;

  onMount(() => {
    if (!element) {
      return;
    }

    const listener = (event: Event) => {
      const changeEvent = event as CustomEvent<OreDropdownChangeDetail>;
      local.onChange?.(changeEvent);
      local.onValueChange?.(changeEvent.detail.value);
    };
    element.addEventListener("change", listener);
    onCleanup(() => element?.removeEventListener("change", listener));
  });

  return (
    <div
      {...rest}
      class={`ore-dropdown ${local.class ?? ""}`}
      data-value={local.value}
      data-variant={local.variant ?? "borderless"}
      ref={(value) => {
        element = value;
        if (typeof local.ref === "function") {
          local.ref(value);
        }
      }}
    />
  );
}
