// packages/react/src/components/progress-bar.ts
import React from "react";

export type ProgressBarProps =
  React.ProgressHTMLAttributes<HTMLProgressElement>;

export const ProgressBar = React.forwardRef<
  HTMLProgressElement,
  ProgressBarProps
>(function ProgressBar(props, ref) {
  return React.createElement("progress", {
    ...props,
    ref,
    className: props.className
      ? `ore-progress-bar ${props.className}`
      : "ore-progress-bar",
  });
});

// packages/solid/src/components/progress-bar.tsx
import { splitProps, type JSX } from "solid-js";

export type ProgressBarProps = JSX.ProgressHTMLAttributes<HTMLProgressElement>;

export function ProgressBar(props: ProgressBarProps): JSX.Element {
  const [local, rest] = splitProps(props, ["class"]);

  return (
    <progress
      {...rest}
      class={`ore-progress-bar ${local.class ?? ""}`}
    />
  );
}
