// packages/svelte/src/components/radio.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";

  export type RadioProps = Omit<HTMLInputAttributes, "children" | "color" | "type"> & {
    children?: Snippet;
    color?: string;
    labelClass?: string;
  };

  let {
    children,
    class: className,
    color,
    labelClass,
    ...props
  }: RadioProps = $props();
  let element: HTMLInputElement;

  export function getElement(): HTMLInputElement {
    return element;
  }
</script>

<label class={labelClass}>
  <input bind:this={element} {...props} class="ore-radio {className ?? ''}" data-color={color} type="radio" />
  {@render children?.()}
</label>

// packages/solid/src/components/radio.tsx
import { splitProps, type JSX } from "solid-js";

export type RadioProps = Omit<
  JSX.InputHTMLAttributes<HTMLInputElement>,
  "color" | "type"
> & {
  color?: string;
  labelClass?: string;
  onCheckedChange?: (checked: boolean) => void;
};

export function Radio(props: RadioProps): JSX.Element {
  const [local, inputProps] = splitProps(props, [
    "children",
    "class",
    "color",
    "labelClass",
    "onCheckedChange",
    "onInput",
  ]);

  return (
    <label class={local.labelClass}>
      <input
        {...inputProps}
        class={`ore-radio ${local.class ?? ""}`}
        data-color={local.color}
        onInput={(event) => {
          if (typeof local.onInput === "function") {
            local.onInput(event);
          }
          local.onCheckedChange?.(event.currentTarget.checked);
        }}
        type="radio"
      />
      {local.children}
    </label>
  );
}
