// packages/svelte/src/components/select.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLSelectAttributes } from "svelte/elements";

  export type SelectProps = Omit<HTMLSelectAttributes, "children" | "value"> & {
    children?: Snippet;
    value?: string;
    onChange?: (event: Event) => void;
  };

  let {
    children,
    class: className,
    value = $bindable(""),
    onChange,
    ...props
  }: SelectProps = $props();
  let element: HTMLSelectElement;

  function handleChange(event: Event): void {
    value = element.value;
    onChange?.(event);
  }

  export function getElement(): HTMLSelectElement {
    return element;
  }
</script>

<select bind:this={element} bind:value class="ore-select {className ?? ''}" onchange={handleChange} {...props}>
  {@render children?.()}
</select>

// packages/solid/src/components/select.tsx
import { splitProps, type JSX } from "solid-js";

export type SelectProps = Omit<
  JSX.SelectHTMLAttributes<HTMLSelectElement>,
  "onChange"
> & {
  onChange?: (event: Event & { currentTarget: HTMLSelectElement }) => void;
  onValueChange?: (value: string) => void;
};

export function Select(props: SelectProps): JSX.Element {
  const [local, selectProps] = splitProps(props, [
    "class",
    "onChange",
    "onValueChange",
  ]);

  return (
    <select
      {...selectProps}
      class={`ore-select ${local.class ?? ""}`}
      onChange={(event) => {
        local.onChange?.(event);
        local.onValueChange?.(event.currentTarget.value);
      }}
    />
  );
}
