// packages/react/src/components/select.tsx
import React from "react";

export type SelectProps = Omit<
  React.SelectHTMLAttributes<HTMLSelectElement>,
  "color"
>;

export const Select = React.forwardRef<HTMLSelectElement, SelectProps>(
  function Select(props, ref): React.ReactElement {
    const { className, ...selectProps } = props;

    return (
      <select
        {...selectProps}
        className={className ? `ore-select ${className}` : "ore-select"}
        ref={ref}
      />
    );
  },
);

// packages/solid/src/components/select.tsx
import { splitProps, type JSX } from "solid-js";

export type SelectProps = Omit<
  JSX.SelectHTMLAttributes<HTMLSelectElement>,
  "onChange"
> & {
  onChange?: (event: Event & { currentTarget: HTMLSelectElement }) => void;
  onValueChange?: (value: string) => void;
};

export function Select(props: SelectProps): JSX.Element {
  const [local, selectProps] = splitProps(props, [
    "class",
    "onChange",
    "onValueChange",
  ]);

  return (
    <select
      {...selectProps}
      class={`ore-select ${local.class ?? ""}`}
      onChange={(event) => {
        local.onChange?.(event);
        local.onValueChange?.(event.currentTarget.value);
      }}
    />
  );
}
