// packages/react/src/components/tag.tsx
import React from "react";

export type TagProps = React.HTMLAttributes<HTMLSpanElement> & {
  variant?: string;
  outlined?: boolean;
};

export const Tag = React.forwardRef<HTMLSpanElement, TagProps>(function Tag(
  { children, variant, outlined, ...props },
  ref,
) {
  return (
    <span
      {...props}
      ref={ref}
      className={props.className ? `ore-tag ${props.className}` : "ore-tag"}
      data-variant={variant}
      data-outlined={outlined ? "" : undefined}
    >
      {children}
    </span>
  );
});

// packages/solid/src/components/tag.tsx
import type { JSX } from "solid-js";

export type TagProps = JSX.HTMLAttributes<HTMLSpanElement> & {
  variant?: string;
  outlined?: boolean;
};

export function Tag(props: TagProps): JSX.Element {
  const { variant, outlined, class: className, ...rest } = props;

  return (
    <span
      {...rest}
      class={`ore-tag ${className ?? ""}`}
      data-variant={variant}
      data-outlined={outlined ? "" : undefined}
    />
  );
}
