// packages/react/src/components/textarea.tsx
import React from "react";

export type TextareaProps = Omit<
  React.TextareaHTMLAttributes<HTMLTextAreaElement>,
  "children" | "color"
> & {
  description?: string;
  error?: string;
  label?: string;
};

export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  function Textarea(
    { className, description, error, id, label, onInput, style, ...props },
    ref,
  ): React.ReactElement {
    const generatedId = React.useId();
    const textareaId = id ?? `ore-textarea-${generatedId}`;
    const descriptionId = description ? `${textareaId}-description` : undefined;
    const errorId = error ? `${textareaId}-error` : undefined;
    const describedBy = [descriptionId, errorId].filter(Boolean).join(" ");
    const textareaRef = React.useRef<HTMLTextAreaElement | null>(null);

    React.useEffect(() => {
      textareaRef.current?.setCustomValidity(error ?? "");
    }, [error]);

    return (
      <div
        className={className ? `ore-textarea ${className}` : "ore-textarea"}
        style={style}
      >
        {label ? (
          <label className="ore-textarea-label" htmlFor={textareaId}>
            {label}
          </label>
        ) : null}
        <span className="ore-textarea-control">
          <textarea
            {...props}
            ref={(element) => {
              textareaRef.current = element;
              if (typeof ref === "function") {
                ref(element);
              } else if (ref) {
                ref.current = element;
              }
            }}
            aria-describedby={describedBy || undefined}
            aria-invalid={error ? true : undefined}
            className="ore-textarea-input"
            id={textareaId}
            onInput={onInput}
          />
        </span>
        {description ? (
          <span className="ore-textarea-description" id={descriptionId}>
            {description}
          </span>
        ) : null}
        {error ? (
          <span className="ore-textarea-error" id={errorId} aria-live="polite">
            {error}
          </span>
        ) : null}
      </div>
    );
  },
);

// packages/solid/src/components/textarea.tsx
import { createRenderEffect, splitProps, type JSX } from "solid-js";

export type TextareaProps = Omit<
  JSX.TextareaHTMLAttributes<HTMLTextAreaElement>,
  "children" | "oninput" | "value"
> & {
  children?: JSX.Element;
  description?: string;
  error?: string;
  label?: string;
  onInput?: (
    event: InputEvent & { currentTarget: HTMLTextAreaElement },
  ) => void;
  value?: string;
  onValueChange?: (value: string) => void;
};

export function Textarea(props: TextareaProps): JSX.Element {
  const [local, textareaProps] = splitProps(props, [
    "children",
    "description",
    "error",
    "id",
    "label",
    "class",
    "onInput",
    "onValueChange",
    "style",
    "value",
  ]);
  let element: HTMLTextAreaElement | undefined;
  const generatedId = `ore-textarea-${crypto.randomUUID()}`;

  createRenderEffect(() => {
    element?.setCustomValidity(local.error ?? "");
  });

  const textareaId = () => local.id ?? generatedId;
  const descriptionId = () =>
    local.description ? `${textareaId()}-description` : undefined;
  const errorId = () => (local.error ? `${textareaId()}-error` : undefined);

  return (
    <div
      class="ore-textarea"
      classList={{ [local.class ?? ""]: true }}
      style={local.style}
    >
      {local.label ? (
        <label class="ore-textarea-label" for={textareaId()}>
          {local.label}
        </label>
      ) : null}
      <span class="ore-textarea-control">
        {local.children}
        <textarea
          {...textareaProps}
          aria-describedby={
            [descriptionId(), errorId()].filter(Boolean).join(" ") || undefined
          }
          aria-invalid={local.error ? "true" : undefined}
          class="ore-textarea-input"
          id={textareaId()}
          onInput={(event) => {
            local.onInput?.(event);
            local.onValueChange?.(event.currentTarget.value);
          }}
          ref={(value) => {
            element = value;
          }}
          value={local.value}
        />
      </span>
      {local.description ? (
        <span class="ore-textarea-description" id={descriptionId()}>
          {local.description}
        </span>
      ) : null}
      {local.error ? (
        <span class="ore-textarea-error" id={errorId()} aria-live="polite">
          {local.error}
        </span>
      ) : null}
    </div>
  );
}
