// packages/svelte/src/components/toast.svelte
<script lang="ts">
  import "oreui-web/toast";
  import type { OreToastPosition, OreToastVariant } from "oreui-web/toast";
  import { onMount } from "svelte";
  import type { OreComponentProps } from "../types.js";

  export type ToastProps = OreComponentProps<HTMLDivElement> & {
    defaultOpen?: boolean;
    duration?: number;
    open?: boolean;
    position?: OreToastPosition;
    variant?: OreToastVariant;
    onOpenChange?: (event: CustomEvent<boolean>) => void;
  };

  let {
    children,
    class: className,
    defaultOpen = false,
    duration,
    open,
    position = "bottom-center",
    variant = "neutral",
    onOpenChange,
    ...props
  }: ToastProps = $props();
  let element: HTMLDivElement;

  onMount(() => {
    const listener = (event: Event): void => {
      onOpenChange?.(event as CustomEvent<boolean>);
    };
    element.addEventListener("oreui:openchange", listener);
    return () => element.removeEventListener("oreui:openchange", listener);
  });

  export function getElement(): HTMLDivElement {
    return element;
  }
</script>

<div
  bind:this={element}
  class={`ore-toast ${className ?? ""}`}
  data-default-open={defaultOpen ? "" : undefined}
  data-duration={duration}
  data-open={open ? "" : undefined}
  data-position={position}
  data-variant={variant}
  {...props}
>
  {@render children?.()}
</div>

// packages/solid/src/components/toast.tsx
import "oreui-web/toast";

import type { OreToastPosition, OreToastVariant } from "oreui-web/toast";
import { onCleanup, onMount, splitProps, type JSX } from "solid-js";

export type ToastProps = JSX.HTMLAttributes<HTMLDivElement> & {
  defaultOpen?: boolean;
  duration?: number;
  onOpenChange?: (event: CustomEvent<boolean>) => void;
  open?: boolean;
  position?: OreToastPosition;
  variant?: OreToastVariant;
};

export function Toast(props: ToastProps): JSX.Element {
  const [local, rest] = splitProps(props, [
    "class",
    "defaultOpen",
    "duration",
    "onOpenChange",
    "open",
    "position",
    "ref",
    "variant",
  ]);
  let element: HTMLDivElement | undefined;

  onMount(() => {
    if (!element) {
      return;
    }
    const listener = (event: Event): void => {
      local.onOpenChange?.(event as CustomEvent<boolean>);
    };
    element.addEventListener("oreui:openchange", listener);
    onCleanup(() => element?.removeEventListener("oreui:openchange", listener));
  });

  return (
    <div
      {...rest}
      class={`ore-toast ${local.class ?? ""}`}
      data-default-open={local.defaultOpen ? "" : undefined}
      data-duration={local.duration}
      data-open={local.open ? "" : undefined}
      data-position={local.position ?? "bottom-center"}
      data-variant={local.variant ?? "neutral"}
      ref={(value) => {
        element = value;
        if (typeof local.ref === "function") {
          local.ref(value);
        }
      }}
    />
  );
}
